//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaderboardProject.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class scores
    {
        public int Id { get; set; }
        public string GamerName { get; set; }
        public Nullable<System.DateTime> Day { get; set; }
        public Nullable<float> Score { get; set; }
        public Nullable<int> game_id { get; set; }
    
        public virtual games games { get; set; }
    }
}
